Sprints/Sprint 1/StudentScheduler/StudentScheduler/Models/UserMajorRequirement.cs
namespace StudentScheduler.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class UserMajorRequirement
    {
        public int ID { get; set; }

        [Required]
        [StringLength(128)]
        public string UserID { get; set; }

        public int ReqID { get; set; }

        [DisplayName("Requirement Met")]
        public bool ReqMet { get; set; }

        //public virtual AspNetUser AspNetUser { get; set; }

        public virtual Requirement Requirement { get; set; }
    }
}

Sprints/Sprint 1/StudentScheduler/StudentScheduler/Controllers/UserMajorRequirementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using StudentScheduler.DAL;
using StudentScheduler.Models;
using Microsoft.AspNet.Identity;

namespace StudentScheduler.Controllers
{
    public class UserMajorRequirementsController : Controller
    {
        private ApplicationUserManager _userManager;
        private SchedulerContext db = new SchedulerContext();

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: UserMajorRequirements
        [Authorize(Roles = "Student")]
        public ActionResult Index()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var major = db.Majors.FirstOrDefault(m => m.ID == user.MajorId);
            var userMajorRequirements = db.UserMajorRequirements.Where(u => u.UserID == user.Id).Include(u => u.Requirement);
            ViewBag.Head = "My Requirements for " + major.Title + ":";
            return View(userMajorRequirements.ToList());
        }

        // POST: UserMajorRequirements/SetMetReqs
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Student")]
        [ValidateAntiForgeryToken]
        public ActionResult SetMetReqs(FormCollection form)
        {
            // Get collection of of selected met requirements
            var checkedValues = form.GetValues("reqMetChkBox");
            var userID = User.Identity.GetUserId();

            IQueryable<UserMajorRequirement> userMajorReqs = db.UserMajorRequirements.Where(umr => umr.UserID == userID);
            foreach ( UserMajorRequirement UMReq in userMajorReqs)
            {
                if (checkedValues == null)
                {
                    UMReq.ReqMet = false;
                }
                else
                {
                    UMReq.ReqMet = (Array.IndexOf(checkedValues, UMReq.ID.ToString()) > -1);
                }
                db.Entry(UMReq).State = EntityState.Modified;
            }
            db.SaveChanges();

            return RedirectToAction("InfoList","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sprints/Sprint 1/StudentScheduler/StudentScheduler/Views/UserMajorRequirements/Index.cshtml
@model IEnumerable<StudentScheduler.Models.UserMajorRequirement>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "My Requirements";
    var wGrid = new WebGrid(Model, rowsPerPage: 200);
}
<div class="gumbotron">

    <h2>@ViewBag.Title</h2>
    @Html.ActionLink("Back to Info List", "InfoList", "Home", null, new { @class = "btn btn-outline-primary" })
    <br />

    @using (Html.BeginForm("SetMetReqs", "UserMajorRequirements"))
    {
        @Html.AntiForgeryToken()
        <div id="grid">
            @wGrid.GetHtml(
            tableStyle: "table table-responsive table-striped table-bordered",

            columns: wGrid.Columns(
                wGrid.Column(header: "Requirement Title", format:@<text>@item.Requirement.RequirementTitle</text>),
                                               wGrid.Column(header: "Requirement Description", format:@<text>@item.Requirement.RequirementDescription</text>),
                                                                        wGrid.Column(header: "Completed", format:@<text><input class="check-box" name="reqMetChkBox" type="checkbox" value="@item.ID" @(item.ReqMet == true ? "Checked" : null) /></text>)))
        </div>

        <input type="submit" value="Save Changes" class="btn btn-outline-primary btn-sm" /><span>&nbsp; &nbsp;</span>@Html.ActionLink("Cancel", "InfoList", "Home", null, new { @class = "btn btn-outline-primary btn-sm" })
    }
</div>