Sprints/Sprint 1/StudentScheduler/StudentScheduler/Models/Upload.cs
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StudentScheduler.Models
{
    public class Upload
    {
        [Required(ErrorMessage = "Please select file")]
        public HttpPostedFileBase file { get; set; }
    }
}

Sprints/Sprint 1/StudentScheduler/StudentScheduler/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Net;
using System.Data;
using System.Data.Entity;
using OfficeOpenXml;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Configuration;
//using Excel = Microsoft.Office.Interop.Excel;
using StudentScheduler.DAL;
using StudentScheduler.Models;
using StudentScheduler.Models.ViewModels;
using System.Runtime.InteropServices;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;

namespace StudentScheduler.Controllers
{
    public class UploadController : Controller
    {
        private ApplicationUserManager _userManager;
        private SchedulerContext db = new SchedulerContext();
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(object sender, EventArgs e, StudentScheduler.Models.Upload importExcel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string filepath = Server.MapPath("~/Content/" + importExcel.file.FileName);
                    importExcel.file.SaveAs(filepath);
                    using (SpreadsheetDocument doc = SpreadsheetDocument.Open(filepath, false))
                    {
                        WorkbookPart wbPart = doc.WorkbookPart;
                        int worksheetcount = doc.WorkbookPart.Workbook.Sheets.Count();
                        Sheet mysheet = (Sheet)doc.WorkbookPart.Workbook.Sheets.ChildElements.GetItem(0);
                        Worksheet Worksheet = ((WorksheetPart)wbPart.GetPartById(mysheet.Id)).Worksheet;
                        int wkschildno = 4;
                        SheetData Rows = (SheetData)Worksheet.ChildElements.GetItem(wkschildno);
                        Row currentrow = (Row)Rows.ChildElements.GetItem(0);
                        Cell currentcell = (Cell)currentrow.ChildElements.GetItem(0);
                        List<Completion> comps = new List<Completion>();
                        string currentcellvalue = string.Empty;
                        for (int j = 1; j < Rows.Count(); j++)
                        {
                            string reqs = "";
                            string subtext = "";
                            int CredReq = 0;
                            int CredComp = 0;
                            string taken = "";
                            for (int i = 0; i < 5; i++)
                            {
                                currentrow = (Row)Rows.ChildElements.GetItem(j);
                                try
                                {
                                    currentcell = (Cell)currentrow.ChildElements.GetItem(i);
                                    if (currentcell.DataType != null)
                                    {
                                        //Console.Write("hey");
                                        if (currentcell.DataType == CellValues.SharedString)
                                        {
                                            int id = -1;

                                            if (Int32.TryParse(currentcell.InnerText, out id))
                                            {
                                                SharedStringItem item = GetSharedStrings(wbPart, id);

                                                if (item.Text != null)
                                                {
                                                    //code to take the string value  
                                                    currentcellvalue = item.Text.Text;
                                                    if (currentcellvalue.Contains(','))
                                                    {
                                                        int num;
                                                        num = Convert.ToInt32(currentcellvalue.Substring(0, currentcellvalue.LastIndexOf(',')));
                                                        if (i == 2)
                                                        {
                                                            CredReq = num;
                                                        }
                                                        else if (i == 3)
                                                        {
                                                            CredComp = num;
                                                        }
                                                    }
                                                    else
                                                    {
                                                        if (i == 0)
                                                        {
                                                            reqs = currentcellvalue;
                                                        }
                                                        else if (i == 1)
                                                        {
                                                            subtext = currentcellvalue;
                                                        }
                                                        else if (i == 4)
                                                        {
                                                            taken = currentcellvalue; ;
                                                        }
                                                    }
                                                }
                                                else if (item.InnerText != null)
                                                {
                                                    currentcellvalue = item.InnerText;
                                                    if (i == 0)
                                                    {
                                                        reqs = currentcellvalue;
                                                    }
                                                    else if (i == 1)
                                                    {
                                                        subtext = currentcellvalue;
                                                    }
                                                    else if (i == 4)
                                                    {
                                                        taken = currentcellvalue; ;
                                                    }
                                                }
                                                else if (item.InnerXml != null)
                                                {
                                                    currentcellvalue = item.InnerXml;
                                                }
                                            }
                                            else
                                            {
                                            }
                                        }
                                    }
                                }
                                catch (Exception ec)
                                {
                                    taken = "";
                                }

                            }
                            Completion p = new Completion();
                            p.UserID = User.Identity.GetUserId();
                            p.Requirements = reqs;
                            p.Subtexts = subtext;
                            p.CreditsRequired = CredReq;
                            p.CreditsCompleted = CredComp;
                            p.ClassesTaken = taken;
                            comps.Add(p);
                            db.Completions.Add(p);
                            db.SaveChanges();
                        }

                    }
                    System.IO.File.Delete(filepath);
                }
                catch (Exception Ex)
                {

                    Console.WriteLine(Ex.Message);
                }
            }
            
            return View();
        }
        public ActionResult Progress()
        {
            string userId = User.Identity.GetUserId();
            IQueryable<CompletionVM> comps = null;
            IQueryable<CompletionVM> toDo = db.Completions.Select(c => new CompletionVM
            {
                UserID = c.UserID,
                Requirements = c.Requirements,
                Subtexts = c.Subtexts,
                ClassesTaken = c.ClassesTaken,
                CreditsCompleted = c.CreditsCompleted,
                CreditsRequired = c.CreditsRequired
            }).Where(com => com.CreditsCompleted < com.CreditsRequired).Where(com =>com.UserID == userId);
            if(toDo.Count() > 0)
            {
                ViewBag.toggle = 1;
                ViewBag.result = "These are the requirements you have not met yet";
            }
            return View(toDo.ToList());
        }
        public static SharedStringItem GetSharedStrings(WorkbookPart workbookPart, int id)
        {
            return workbookPart.SharedStringTablePart.SharedStringTable.Elements<SharedStringItem>().ElementAt(id);
        }
    }
}

Sprints/Sprint 1/StudentScheduler/StudentScheduler/Views/Upload/Index.cshtml
@model StudentScheduler.Models.Upload
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="relative" style="margin-bottom:0">
    <h2 class="absoluteA" style="text-align: center;">
        Upload Your Information
    </h2>
    <p class="absoluteB">
        By uploading your current school DegreeTracks and other relevant information, we can better assist you with your scheduling. 
        For our site please make sure that your file is created and filled with Excel. 
    </p>
    <img src="~/Content/infoHelp.png" class="absoluteC"/>
</div>
<div class="uploadInput">
    <h4>@ViewBag.Result</h4>
    @using (Html.BeginForm("Index", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.TextBoxFor(m => m.file, new { type = "file" })
        <button id="submitButton" type="submit">Submit</button>
        @Html.ValidationMessageFor(model => model.file)
    }
    <br />
    <div>@Html.ActionLink("Show Progress", "Progress", "Upload")</div>
</div>
<br />
<br />
    @Html.ActionLink("Back to Info List", "InfoList", "Home", null, new { @class = "btn btn-outline-primary" })

Sprints/Sprint 1/StudentScheduler/StudentScheduler/Views/Upload/Index2.cshtml
@{
    ViewBag.Title = "Index";
}
<head>

    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <title>Import Degree Progress</title>
</head>
<style>
    .fileUpload {
        position: relative;
        overflow: hidden;
        margin: 10px;
    }

    .upload {
        top: 0;
        right: 0;
        margin: 0;
        padding: 0;
        font-size: 20px;
        cursor: pointer;
        opacity: 0;
        filter: alpha(opacity=0);
    }

    .head {
        background-color: greenyellow;
    }

        .head tr th {
            text-align: center;
            font-weight: bold;
        }
</style>

<div class="row" style="padding:15px">
    <div class="col-lg-2 col-md-2 col-sm-6 col-xs-6" id="filePathtxt">
        <label class="Flabel">Choose File Path</label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6" id="filePathInput">

        @using (Html.BeginForm("UploadFile", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="text" class="" id="txtfile" for="uploadXML" />
            <i id="buttonFileLoad" class="fa fa-file pull-right" area-hidden="true" onclick="return fileLoad()" style="margin-top:2px;font-size:21px;position:relative;cursor:pointer;color:forestgreen;left:-172px">

            </i>
            <input type="file" name="UploadedFile" id="fileLoadDoc" accept=".xlsx" />
        }
        <table class="table table-bordered table-responsive table-striped">
            <thead class="head">
            </thead>
            <tbody class="body"></tbody>
        </table>
        <label id="message"></label>
    </div>
</div>
<script>
    $(function () {
        $('input[type="file"]').change(function (e) {
            debugger
            var filename = e.target.files[0].name;
            var Files = $("#fileLoadDoc").get(0);
            $("#txtfile").val(filename);
            $("#btnsbmt").trigger("click");
            formdata = new FormData();
            for (var i = 0; i < e.target.files.length; i++) {
                formdata.append(e.target.files[i].name, e.target.files[i]);
            }
            $.ajax({
                url: '@Url.Action("UploadFile", "Upload")',
                type: "POST",
                datatype: "JSON",
                contentType: false,
                processData: false,
                data: formdata,
                success: function (result) {
                    debugger
                    var count = 0;
                    if (result != null) {
                        debugger
                        $("#message").css('color','green').text("Thanks for uploading your degree progress!")
                        $(".head").empty();
                        $(".body").empty();
                        for (var i = 0; i < result.row; i++) {
                            if (i == 0) {
                                $(".head").append("<tr>");
                            }
                            else {
                                $(".body").append("<tr class='tr"+i+"'>");
                            }
                            for (var j = 0; j < result.col; j++) {
                                if (i==0) {
                                    $(".head tr").append("<th>" + result.data[count] + "</th>");
                                }
                                else
                                {
                                    if (result.data[count]!=null) {
                                        $(".body .tr" + i + "").append("<td>" + result.data[count] + "</td>");
                                    }
                                    else
                                    {
                                        $(".body .tr" + i + "").append("<td></td>");
                                    }
                                }
                                count++;
                            }
                            if (i == 0) {
                                $(".head").append("</tr>");

                            }
                            else
                            {
                                $(".body .tr"+i+"").append("</tr>");
                            }
                        }
                    }
                    else
                    {
                        $("#message").css('color', 'red').text("Sorry, there seems to be an error!")
                    }
                }
            })
        });
    });
    function fileLoad() {
        debugger
        $('#txtfile').val("");
        $('#fileLoadDoc').val("");
        $('#buttonFileLoad').val("");
        $("#fileLoadDoc").trigger('click');
    }
</script>

Sprints/Sprint 1/StudentScheduler/StudentScheduler/Views/Upload/Progress.cshtml
@model IEnumerable<StudentScheduler.Models.ViewModels.CompletionVM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h2>Progress</h2>

<h1 style="color: mediumturquoise;">These are the requirments you have yet to satisfy</h1>
<div class="row overflow-x:auto;">
    <!--This will show up if there are results-->
    @if (ViewBag.toggle == 1)
    {
    <div class="col-md-4">
            <table class="table">
                <tr style="background-color: mediumturquoise">
                    <th>
                        @Html.DisplayNameFor(model => model.Requirements)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreditsRequired)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Subtexts)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ClassesTaken)
                    </th>
                    <th></th>
                </tr>
                <!-- Display actual table information -->
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Requirements)
                        </td>
                        <td>
                            @(item.CreditsRequired - item.CreditsCompleted)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subtexts)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ClassesTaken)
                        </td>
                    </tr>
                }

            </table>
    </div>
    }
</div>